#!/bin/sh

cd ${LAMBDA_TASK_ROOT:-.}

java -Dspring.main.web-application-type=none \
  -noverify -XX:TieredStopAtLevel=1 -Xss256K -XX:MaxMetaspaceSize=48M -Xmx8m \
  -cp .:`echo lib/*.jar | tr ' ' :` com.example.demo.serverless.ServerlessApplication
